= Hostsharing Billing Core
Michael Hönnig
2020-12-03
:icons: font

== Code-Formatting and Linting

The general formatting of files is defined in `.editorconfig`, these settings should automatically be picked up by most code editors and IDSs.

Also, _ktlint_ is installed and configured.
To check code style, run:

[source,shell script]
----
$ ./gradlew ktlint
----

This task also bound to "gradle check".

To automatically fix code style deviations, use:

[source,shell script]
----
$ ./gradlew ktlintFormat
----

== Unit Testing

For unit-testing, _JUnit 5 (Jupiter)__ is used along with _assertk_, a _Kotlin_ version of _assertj_.

To execute the unit-tests, run:

[source,shell script]
----
$ ./gradlew test
----

For writing unit-tests consider the __BRIEF__ rules http://gasparnagy.com/2019/05/clean-up-bad-bdd-scenarios/[from BDD]:

Business language::
enables collaboration and feedback

Real data::
helps to discover white spots in requirements

Intention revealing::

is a way to describe the tests by focusing on what we wanted to achieve and not on how

Essential::
include only relevant details in the scenario

Focused::
the scenarios should illustrate a single rule only
Brief — keep scenarios short


== Architecture Verification

There is some automatic verification of architecture rules using __ArchUnit__ in the unit test `ArchitectureTest`.
See there for more information, especially about the git branch `archunit-rule-validation` and verifying the rules themselves.

Technically this is a mal unit-test, thus run with:

[source,shell script]
----
$ ./gradlew test
----


== Mutation Testing

To check the quality of the assertions in the unit-tests, https://pitest.org/[_pitest_] is used as a https://en.wikipedia.org/wiki/Mutation_testing[mutation testing]-tool.

The mutation-tests can be executed with:

[source,shell script]
----
$ ./gradlew pitest
----

This creates link:./app/build/reports/pitest/org.hostsharing.hsadmin.billing.core.reader/index.html[a report] comprising line- and mutation-coverage of the unit-tests.

If the "mutant-kill rate" falls below a configured limit, the _pitest_-task  will fail;
in that case, please improve the unit-tests.
The limits are configured in `app/build.gradle`.
Please increase the limit according to the level we have reached, once we become better;
about 2 percent points below the level we have actually reached, is a good measure.

CAUTION: After a successful run, you can see percentage  which actually counts for the limit.
The percentage shown in the report HTML-file seems to be calculated differently and is usually a bit higher.
