
== Code-Formatting and Linting

The general formatting of files is defined in `.editorconfig`, these settings should automatically be picked up by most code editors and IDSs.

Also, _ktlint_ is installed and configured.
To check code style, run:

[source,shell script]
----
$ ./gradlew ktlint
----

This task also bound to "gradle check".

To automatically fix code style deviations, use:

[source,shell script]
----
$ ./gradlew ktlintFormat
----

== Unit Testing

For unit-tests consider the __BRIEF__ rules http://gasparnagy.com/2019/05/clean-up-bad-bdd-scenarios/[from BDD]:

Business language::
enables collaboration and feedback

Real data::
helps to discover white spots in requirements

Intention revealing::

is a way to describe the tests by focusing on what we wanted to achieve and not on how

Essential::
include only relevant details in the scenario

Focused::
the scenarios should illustrate a single rule only
Brief — keep scenarios short



== Architecture Verification

There is some automatic verification of architecture rules using __ArchUnit__ in the unit test `ArchitectureTest`.
See there for more information.

== Mutation Testing

./gradlew pitest

creates: link:./app/build/reports/pitest/org.hostsharing.hsadmin.billing.core.reader/index.html[]

configuration of limits in app/build.gradle

Please increase the limit according to what we have reached, once we became better.
